version: '3.8'

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even 
    networks:
      - db
networks:
  db:
    driver: bridge
volumes:
  database-data:
