version: '3.8'

services:
  database:
    image: "postgres" # use latest official postgres version
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even 
    networks:
      - db
    ports:
      - 5000:5432
networks:
  db:
    driver: bridge
volumes:
  database-data:
